ARG DEPRECATED_VERSION=release-v1.8.1
FROM bash
ARG DEPRECATED_VERSION
COPY ./CRITICAL_ALERT.rst /CRITICAL_ALERT.rst
COPY ./entrypoint /entrypoint
RUN sed -i "s|\${DEPRECATED_VERSION}|${DEPRECATED_VERSION}|g" /CRITICAL_ALERT.rst
ENTRYPOINT [ "/entrypoint" ]
